package com.example.myapplication.ui.theme

import androidx.compose.ui.graphics.Color

// Macaco brand gold — used for tag text across the app (matches the splash logo gold).
val MacacoGold = Color(0xFFE8B020)

// Light theme — warm leather & open-sky palette
val md_light_primary = Color(0xFF2D6B6B)
val md_light_onPrimary = Color(0xFFFFFFFF)
val md_light_primaryContainer = Color(0xFFB2E5E5)
val md_light_onPrimaryContainer = Color(0xFF002020)
val md_light_secondary = Color(0xFF7D5A40)
val md_light_onSecondary = Color(0xFFFFFFFF)
val md_light_secondaryContainer = Color(0xFFF7D9C0)
val md_light_onSecondaryContainer = Color(0xFF2E1500)
val md_light_tertiary = Color(0xFF8B4513)
val md_light_onTertiary = Color(0xFFFFFFFF)
val md_light_tertiaryContainer = Color(0xFFFFD9C0)
val md_light_onTertiaryContainer = Color(0xFF2E0D00)
val md_light_background = Color(0xFFFFF8F0)
val md_light_onBackground = Color(0xFF1F1B17)
val md_light_surface = Color(0xFFFFF8F0)
val md_light_onSurface = Color(0xFF1F1B17)
val md_light_surfaceVariant = Color(0xFFEDE0D3)
val md_light_onSurfaceVariant = Color(0xFF4E4036)
val md_light_outline = Color(0xFF7F7167)
val md_light_error = Color(0xFFBA1A1A)
val md_light_onError = Color(0xFFFFFFFF)

// Dark theme
val md_dark_primary = Color(0xFF7FDCDC)
val md_dark_onPrimary = Color(0xFF003737)
val md_dark_primaryContainer = Color(0xFF1F5050)
val md_dark_onPrimaryContainer = Color(0xFFB2E5E5)
val md_dark_secondary = Color(0xFFE0C0A0)
val md_dark_onSecondary = Color(0xFF4A2D15)
val md_dark_secondaryContainer = Color(0xFF63412A)
val md_dark_onSecondaryContainer = Color(0xFFF7D9C0)
val md_dark_tertiary = Color(0xFFFFB889)
val md_dark_onTertiary = Color(0xFF4B1E00)
val md_dark_tertiaryContainer = Color(0xFF6B2E00)
val md_dark_onTertiaryContainer = Color(0xFFFFD9C0)
val md_dark_background = Color(0xFF1A1410)
val md_dark_onBackground = Color(0xFFEEE0D5)
val md_dark_surface = Color(0xFF1A1410)
val md_dark_onSurface = Color(0xFFEEE0D5)
val md_dark_surfaceVariant = Color(0xFF4E4036)
val md_dark_onSurfaceVariant = Color(0xFFD2C4B7)
val md_dark_outline = Color(0xFF9B8E83)
val md_dark_error = Color(0xFFFFB4AB)
val md_dark_onError = Color(0xFF690005)
